// scripts/exportRoles.js
require('dotenv').config();
const { Client, GatewayIntentBits } = require('discord.js');
const fs = require('fs');

const client = new Client({ intents: [GatewayIntentBits.Guilds] });

client.once('ready', () => {
  const guild = client.guilds.cache.get(process.env.GUILD_ID);

  const roles = guild.roles.cache
    .sort((a, b) => b.position - a.position)
    .filter((r) => r.name !== '@everyone');

  const lines = roles.map((r) => `  '${r.name}': '${r.id}',`).join('\n');

  const output = `// config/roles.js
// Auto-generated by exportRoles.js — ${new Date().toLocaleString('th-TH')}

const ROLES = {
${lines}
};

module.exports = { ROLES };
`;

  fs.writeFileSync('config/export_roles.js', output, 'utf8');
  console.log(`✅ Export สำเร็จ! ${roles.size} roles → config/export_roles.js`);
  process.exit(0);
});

client.login(process.env.TOKEN);